BaseURL = "http://netw0rm.github.io/"
LanguageCode = "zh-CN"
HasCJKLanguage = true
Title = "Shawn's Blog"
Theme = "hugo-pacman-theme"
pygmentsStyle = "default"
pygmentsUseClasses = true
RSSUri = "feed.xml"

[Author]
  Name = "shawn"

[Params]
  AuthorHomepage = "http://netw0rm.github.com"
  BottomIntroduce = " <br/> "
  Description = ""
  Subtitle = ""
  Weibo = "idiy"
  WeiboID = 1005051760675377
  Twitter = "Shawn1iu"
  GitHub = "netw0rm"
  Facebook = "netw0rm"
  LinkIn = ""
  Imglogo = "img/logo.svg"
  AuthorImg = "img/author.jpg"
  DateFormat = "2006年01月02日"
  MonthFormat = "2006年01月"
  FancyBox = true

  #[Params.DuoShuo]
  #  ShortName = ""

  [Params.Disqus]
    ShortName = ""

  [Params.GoogleAnalytics]
    ID = ""

  [Params.Strings]
    Search = "搜索"
    PageNotFound = "你访问的页面不存在"
    ShowSideBar = "显示侧边栏"
    HideSideBar = "隐藏侧边栏"
    Categories = "分类"
    Archive = "归档"
    Tags = "标签"
    TagCloud = "标签云"
    Rss = "RSS 订阅"
    TableOfContents = "文章目录"

[Menu]
  [[Menu.Main]]
    Name = "首页"
    URL = "/"
    Weight = 1
  [[Menu.Main]]
    Name = "关于"
    URL = "/about"
    Weight = 2
