#!/bin/bash

shopt -s extglob
cd ../
rm -r !(src)
cd src
hugo
mv public/* ../
git add -A :/
git commit -m $(date '+%Y.%m.%d/%H:%M:%S')
git fetch origin
git rebase origin/master

if [ "$1" = "on" ]; then
  git push origin master
elif [ "$1" = "theme" ]; then
  cd ../
  git subtree push --prefix=src/themes/gindoro git@github.com:netw0rm/gindoro.git master
  cd src
fi
