#!/bin/bash

cd ../
rm -r categories css fancybox font highlight img js post tags 关于
cd src
hugo
mv public/* ../
git add -A :/
git commit -m "write"
git fetch origin
git rebase origin/master

if [ "$1" = "on" ]; then
  git push origin master
fi
