#!/bin/sh

cd ../
rm -r categories css fancybox font highlight img js post tags 关于
cd src
hugo
mv public/* ../
git add -A :/
git commit -m "write"
git fetch origin
git rebase origin/master
git push origin master
